config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  resources :to_dos

  root 'to_dos#index'

end

app/models/to_do.rb
class ToDo < ActiveRecord::Base
  
  # Associations 
  belongs_to :user

  # Validations
  validates :title, presence: true
  validates :user_id, presence: true

end

app/models/user.rb
class User < ActiveRecord::Base

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  
  # Associations 
  has_many :to_dos

  # Validations
  validates :email, presence: true
  validates :email, format: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :authenticate_user!
end

app/controllers/to_dos_controller.rb
class ToDosController < ApplicationController

  def index
    @todos = current_user.to_dos 
  end

  def show 
    @todo = ToDo.find(params[:id])
  end
  
  def new 
    @todo = ToDo.new
  end

  def create
    @todo = current_user.to_dos.build(to_do_params) 

    if @todo.save
      redirect_to @todo
    else
      render :new
    end
  end

  def edit
    @todo = ToDo.find(params[:id])
  end

  def update
    @todo = ToDo.find(params[:id])
    
    if @todo.update(to_do_params)
      redirect_to @todo
    else
      render :new
    end
  end

  def destroy
    ToDo.find(params[:id]).destroy!
    redirect_to todos_path
  end

  private

  def to_do_params
    params.require(:to_do).permit(:title)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/to_do_helper.rb
module ToDoHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>WorkshopRails</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <% if user_signed_in? %>
    <p>
      <%= current_user.email %> - 
      <%= link_to('Logout', destroy_user_session_path, :method => :delete) %>        
    </p>
  <% end %>

  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>

  <%= yield %>

</body>
</html>

app/views/to_dos/edit.html.erb
<h1>To Do Edit</h1>

<%= form_for @todo do |f| %>
  <% if @todo.errors.any? %>
    <ul>
      <% @todo.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  <% end %>

  <%= f.text_field :title, placeholder: 'Title' %>

  <%= f.submit %>

<% end %>

<%= link_to 'Back', to_dos_path %>

app/views/to_dos/index.html.erb
<h1>To Do Index</h1>

<%= link_to 'Add new todo', new_to_do_path %>

<ul>
  <% @todos.each do |t| %>

    <li>
      <%= t.title %>
      <%= link_to 'View todo', to_do_path(t) %>
      <%= link_to 'Edit todo', edit_to_do_path(t) %>
      <%= link_to 'Delete todo', t, method: :delete %>
    </li>

  <% end %>
</ul>

app/views/to_dos/new.html.erb
<h1>To Do New</h1>

<%= form_for @todo do |f| %>
  <% if @todo.errors.any? %>
    <ul>
      <% @todo.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  <% end %>

  <%= f.text_field :title, placeholder: 'Title' %>

  <%= f.submit %>

<% end %>

<%= link_to 'Back', to_dos_path %>

app/views/to_dos/show.html.erb
<h1>To Do Show</h1>

<p>Title: <%= @todo.title %></p>
<p>User: <%= @todo.user.email %></p>

<%= link_to 'Back', to_dos_path %>